from variables import _
hello_message = _("Hello! At this difficult time for Ukraine, there are many people who need not only financial but also verbal help. Due to the failure of Putin's plans, he began bombing peaceful cities in order to intimidate people. Many houses, schools, hospitals have already been destroyed and he is not going to stop.\n\nBut he will not succeed! Because we are a strong nation, we are Ukrainians! And now many people need verbal support that you can give them. For you it is a few words, and for someone the psyche or even life will be saved.\n\nYour letters will be sent to random people who need words of support.\n\nWe also ask for your help in finding such people, because often they are your relatives, friends or acquaintances. Or maybe it's Instagram subscribers or people from your Telegram chats. Share with them a link to the bot")
is_correct_question = _("This is your letter. Is it correct?")
cancel = _("Cancel")
hello = _("Hello")
send_me_valentine_from_link = 'Час проявити креатив! Надішли мені валентинку, яку отримає {recipient_fullname}. Це може бути що завгодно - текст, картинка, гіфка, посилання, відео, стікер, голосове або відеоповідомлення, чи, може, навіть пісня.'
incorrect_link = "Схоже ти перейшов по недійсному посиланні... Ти можеш спробувати ще раз, або вказати отримувача самостійно за допомогою команди /new"
ask_for_username = 'Надішли мені @username або номер телефону людини, якій хочеш відправити анонімне привітання🧚🏼♀️. Можеш також переслати мені повідомлення користувача, якщо його профіль відкритий або надіслати його контакт.'
your_link = 'Твоє посилання:\n{link}\n\nТи можеш поділитися цим посиланням в інстаграмі, размістивши його, наприклад, в біо, тоді інші люди зможуть надіслати тобі валентинку, перейшовши по ньому'
account_is_closed = "На жаль,{forward_sender_name} має закритий акаунт...🤕 Спробуй надіслати @username або номер телефону отримувача"
incorrect_request = 'Некоректний запит. Якщо ти пересилав повідомлення і профіль отримувача закритий, я не зможу надіслати йому повідомлення… Якщо хочеш відправити username, почни його з @, а якщо хочеш написати номер телефону, починай вводити з +'
to_send_letter_press = _("To send letter to someone Ukrainian, press /new")
ask_for_letter_content = _('Send me letter you want to send to someone. It can be text, photo, video, gif, voice, video note or even audio. Press /cancel if you want to do it later')
incorrect_contact = "Проблема з цим контактом. Надішли контакт з номером телефону"
your_letter_will_be_sent_to_1 = _('Your letter:')
your_letter_will_be_sent_to_2 = 'Твоя валентинка буде відправлена <a href="tg://user?id={recipient_id}"> цьому користувачу</a>'
with_number = "з номером"
ask_for_photo = _("Send me photo you want to attach. Press /cancel to return")
ask_for_correct_username = 'Надішли виправлений username або номер телефону. Також ти можеш переслати повідомлення від цієї людини або надіслати його контакт'
ask_for_correct_letter_content = _('Send me new letter')
your_letter_sended_to_admins = _("Your letter will be sent soon. We will notify you.\nPress /new to send new letter.\n\nAlso don`t forget to share bot to relatives, friends, acquaintances, instagram subscribers or people from your telegram chats.\nHelp us to find people who need words of support")
reject = _("Your letter rejected.\nThe reason: {reject_reason}")
block = _("You were blocked.\nThe reason: {block_reason}")
successfull_letter_delivery = _("Your letter has been delivered")
error_letter_delivery = "Ой… під час доставки твоєї валентинки виникла помилка, давай спробуєм ще разок!"
new_answer = _("You got the answer!")
error_answer_delivery = _("Answer not sent, I think the recipient has blocked the bot")
successfull_answer_delivery = _("Answer sent")
new_command = _("Create letter")
my_link_command = "Твоє посилання"
receive_letters_command = _("Receive letters")
not_receive_letters_command = _("Not receive letters")
start_command = _("If you don`t know what to do")
help_command = _("What I can do")
add_admin_command = _("Add admin")
del_admin_command = _("Delete admin")
start_queue_command = _("Start queue")
stop_queue_command = _("Stop queue")
users_command = _("Show users db")
test_letter_command = _("Send test letter")
online_command = _("Receive letters to check")
offline_command = _("Not receive letters to check")
dashboard_scan_timer_command = _("Change scan timer of dashboard")
queue_scan_timer_command = _("Change scan timer of queue")
language_command = _("Change language")
reply_to_answer = _("Щоб відповісти, зроби реплай самого повідомлення, а не цього.")
new_letter = _("You received new letter! You can answer it by reply the message")
button_change_recipient = _('Змінити отримувача')
button_change_content = _('Change letter')
button_del_photo = _("Remove photo")
button_add_photo = _('Add photo')
button_disable_preview = _('Disable preview')
button_enable_preview = _('Enable preview')
button_send_to_admins = _('It is correct')
close = _('Close')
current_language = _('Current language - English')

